# from https://blog.laoda.de/archives/docker-compose-install-wordpress
#
# nano php.ini 
# upload_max_filesize = 512M
# post_max_size = 512M
# memory_limit = 1024M


version: '3.0'
 
services:
  db:
    image: mysql:8.0
    container_name: wordpress-db
    restart: unless-stopped
    command: --max-binlog-size=200M --expire-logs-days=2
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: rootpassword
    volumes:
      - './db:/var/lib/mysql'
    networks:
      - default

  redis:
    image: redis:alpine
    container_name: wordpress-redis
    restart: unless-stopped
    volumes:
      - ./redis/data:/data
    networks:
      - default
 
  app:
    image: wordpress:latest
    container_name: wordpress-app
    restart: unless-stopped
    ports:
      - 8080:80
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: rootp1ass2wo3rd
    volumes:
      - './app/html:/var/www/html'
    links:
      - db:db
    depends_on:
      - redis
      - db
    networks:
      - default
 
networks:
  default:
    name: wordpress
